VersionLiteLoader:False
VersionServerLogin:0
Info:正式版 1.21.1, NeoForge 21.1.248
VersionVanilla:21.0.1
LogoCustom:True
VersionServerAuthServer:https://littleskin.cn/api/yggdrasil
VersionVanillaName:1.21.1
VersionNeoForge:21.1.248
ReleaseTime:2024-08-08 20:24
VersionServerAuthName:LittleSkin 登录
VersionServerAuthRegister:https://littleskin.cn/auth/register
Logo:pack://application:,,,/images/Blocks/Grass.png
VersionArgumentIndieV2:True
IsStar:True
State:7
